/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as HubRouteImport } from './routes/hub'
import { Route as InformasiRouteImport } from './routes/informasi'
import { Route as OrmawaRouteImport } from './routes/ormawa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiRoute = InformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const OrmawaRoute = OrmawaRouteImport.update({
  id: '/ormawa',
  path: '/ormawa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hub': typeof HubRoute
  '/informasi': typeof InformasiRoute
  '/ormawa': typeof OrmawaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hub': typeof HubRoute
  '/informasi': typeof InformasiRoute
  '/ormawa': typeof OrmawaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/hub': typeof HubRoute
  '/informasi': typeof InformasiRoute
  '/ormawa': typeof OrmawaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/galeri' | '/hub' | '/informasi' | '/ormawa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galeri' | '/hub' | '/informasi' | '/ormawa'
  id: '__root__' | '/' | '/galeri' | '/hub' | '/informasi' | '/ormawa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  HubRoute: typeof HubRoute
  InformasiRoute: typeof InformasiRoute
  OrmawaRoute: typeof OrmawaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi': {
      id: '/informasi'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ormawa': {
      id: '/ormawa'
      path: '/ormawa'
      fullPath: '/ormawa'
      preLoaderRoute: typeof OrmawaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  HubRoute: HubRoute,
  InformasiRoute: InformasiRoute,
  OrmawaRoute: OrmawaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
